name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install
        run: npm install
      - name: Test
        env:
          BS_USER: ${{ secret.mac key }}
        run: npx wdio
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: logs
          path: logs
